import { useState } from "react";
import { X, Settings as SettingsIcon, Play, CircleAlert } from "lucide-react";
import { loadModelConfiguration, type ModelConfiguration } from "../lib/intent-api";
import type { AppearancePreferences } from "../lib/appearance";
type Props = { onClose: () => void; appearance: AppearancePreferences; appearanceSaved: boolean; onAppearanceChange: (value: AppearancePreferences) => void };
export function SettingsPanel({ onClose, appearance, appearanceSaved, onAppearanceChange }: Props) {
  const [configuration, setConfiguration] = useState<ModelConfiguration | null>(null);
  const [model, setModel] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const check = async () => { setBusy(true); setError(""); try { setConfiguration(await loadModelConfiguration()); } catch (e) { setError(e instanceof Error ? e.message : "Settings unavailable"); } finally { setBusy(false); } };
  const safeModel = model.trim().replaceAll("'", "'\\''");
  return <div className="template-overlay"><section className="settings-workspace record-workspace" role="dialog" aria-modal="true" aria-labelledby="settings-title"><header className="template-workspace-head"><h2 id="settings-title"><SettingsIcon size={20}/> Settings</h2><button aria-label="Close settings" onClick={onClose}><X size={18}/></button></header><section className="appearance-settings" aria-labelledby="appearance-title"><h3 id="appearance-title">Appearance</h3>
      <label>Interface style<select value={appearance.buttonStyle} onChange={(event) => onAppearanceChange({ ...appearance, buttonStyle: event.target.value === "outline" ? "outline" : "filled" })}><option value="filled">Solid fill</option><option value="outline">Outline · tinted edges</option></select></label>
      <label>Solid-fill text color<select value={appearance.filledText} disabled={appearance.buttonStyle === "outline"} onChange={(event) => onAppearanceChange({ ...appearance, filledText: event.target.value === "white" ? "white" : "black" })}><option value="black">Black</option><option value="white">White</option></select></label>
      <p>{appearance.buttonStyle === "outline" ? "Outline controls and graph blocks use softly tinted top/bottom edges, a clear center and opaque text/icons." : "Solid controls, graph blocks and information sections use the selected text color. Fill shades adapt to keep labels readable."}</p>
      <div className="appearance-preview" aria-label="Button appearance preview"><span className="appearance-sample">Action</span><span className="appearance-sample authorize-button"><CircleAlert size={16}/> Authorize</span><span className="appearance-sample execute-button"><Play size={16} fill="currentColor"/> Execute</span></div>
      <small role="status">{appearanceSaved ? "Changes apply immediately and are remembered in this browser." : "Changes apply for this session. Browser storage is unavailable."}</small>
    </section><h3>Model configuration</h3><p>Model configuration belongs to the terminal that starts the API. This panel checks that running process.</p><button className="context-intent-toggle" disabled={busy} onClick={() => void check()}>{busy ? "Checking…" : "Check API model configuration"}</button>{error && <p role="alert">{error}</p>}{configuration && <div className={configuration.status === "configured" ? "intent-result" : "intent-error"}><strong>{configuration.status === "configured" ? "Model configured · connection not tested" : "Model configuration blocked"}</strong><p>MODEL_NAME: {configuration.model_name_set ? "set" : "missing"} · endpoint: {configuration.model_base_url_set ? "set" : "default"}</p>{configuration.error && <p>{configuration.error}</p>}{configuration.retry_guidance && <p>{configuration.retry_guidance}</p>}</div>}<h3>Configure the launch terminal</h3><label>Installed model name<input value={model} maxLength={200} placeholder="Exact name from ollama list" onChange={(event) => setModel(event.target.value.replace(/[\r\n\x00]/g, ""))}/></label><p>Run <code>ollama list</code> in the terminal where Ollama is installed. Stop ActionCharter, set the exact model name in its launch terminal, then restart:</p><pre>{model.trim() ? `export MODEL_NAME='${safeModel}'\nbash scripts/start_actioncharter.sh` : "export MODEL_NAME='<installed-model-name>'\nbash scripts/start_actioncharter.sh"}</pre><p>Keep your existing MODEL_BASE_URL. For explicitly reviewed write workflows, start with <code>--enable-write-tools</code>. Restarting does not approve work. This panel neither changes the process environment nor calls the model.</p></section></div>;
}
